### PR TITLE
[terra-abstract-modal] Check whether `focus` is defined for the modal trigger element before restoring focus.

### LINKED ISSUE #901: terra-abstract-modal throwing error in IE 10
# Bug Report

## Description
I am using terra-modal-manager version 6.8.0 which uses terra-abstract-modal. In my scenario, I have modal 1 allowing the user to search for items and on selecting any one item, modal 2 pops up. When the modal 2 pops up, I am seeing the following error:

> Object doesn't support property or method 'focus'

## Steps to Reproduce

1. Open Modal 1 
2. Trigger opening of Modal 2 on top of it.
3. Notice the error

## Additional Context / Screenshots
Link: https://github.com/cerner/terra-framework/blob/f788aec29cefd2570a84bd400168a7f830f9c4ae/packages/terra-abstract-modal/src/AbstractModal.jsx#L159

https://teams.microsoft.com/l/message/19:0adf7161dd244f87aa6415f7c5577836@thread.skype/1568980377888?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1568980377888&teamName=Terra&channelName=Component%20Support&createdTime=1568980377888

modalTriggerAsObject

## Expected Behavior
Error should not be seen.

## Possible Solution
No

## Environment

* Component Name and Version: terra-modal-manager 6.8.0
* Browser Name and Version: IE 10
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): Desktop, Windows

## @ Mentions
@nramamurth @ShettyAkarsh

### PR DESCRIPTION
**Pull request by nramamurth**
### Summary
Fixes #901.

### Additional Details
I was able to reproduce this when the modal is disclosed via a non-HTML element (SVG for example). In the test case below, `modalTrigger` is the SVG element (that does not support `focus()`) on IE but it is the `body` element on other major browsers. 

<details> <summary> Reduced Test Case </summary>

```
import React from 'react';
import PropTypes from 'prop-types';
import ContentContainer from 'terra-content-container';
import { withDisclosureManager, disclosureManagerShape } from 'terra-disclosure-manager';
import ModalManager from 'terra-modal-manager';

class DisclosureComponent extends React.Component {
  constructor(props) {
    super(props);

    this.disclose = this.disclose.bind(this);
    this.closeDisclosure = this.closeDisclosure.bind(this);
  }

  disclose(size, dimensions) {
    const { disclosureType, nestedIndex } = this.props;

    const newIndex = nestedIndex + 1;
    return () => {
      this.props.disclosureManager.disclose({
        preferredType: disclosureType,
        size,
        dimensions,
        content: {
          key: `DemoContainer-${newIndex}`,
          component: <WrappedDisclosureComponent identifier={`DemoContainer-${newIndex}`} nestedIndex={newIndex} />,
        },
      });
    };
  }

  closeDisclosure() {
    this.props.disclosureManager.closeDisclosure();
  }

  render() {
    const { disclosureManager, identifier } = this.props;

    return (
      <ContentContainer id={identifier} className="nested-component" fill header={<h2>IE Focus Issue</h2>}>
        <br />
        <div>
          <svg width="75" height="25">
            <g>
              <rect x="0" y="0" width="100%" height="100%" fill="#da552f" />
              <text x="10" y="17" onClick={this.disclose()}>Disclose</text>
            </g>
          </svg>
        </div>
        {disclosureManager && disclosureManager.closeDisclosure ? <button type="button" className="close-disclosure" onClick={this.closeDisclosure}>Close Disclosure</button> : null}
      </ContentContainer>
    );
  }
}

DisclosureComponent.propTypes = {
  disclosureManager: disclosureManagerShape,
  identifier: PropTypes.string,
  disclosureType: PropTypes.string,
  nestedIndex: PropTypes.number,
};

DisclosureComponent.defaultProps = {
  nestedIndex: 0,
};

const WrappedDisclosureComponent = withDisclosureManager(DisclosureComponent);

const ModalManagerDefault = () => (
  <div role="main">
    <ModalManager>
      <WrappedDisclosureComponent identifier="root-component" disclosureType="modal" />
    </ModalManager>
  </div>
);

export default ModalManagerDefault;

```
</details>

<details> <summary> Behavior on IE 10 </summary>

ie-focus-issue
</details>

<details> <summary> Behavior on Chrome </summary> 

chrome-focus-issue
</details>

I have functionally verified the change, btw.

### CODE REVIEW

File: packages/terra-abstract-modal/src/AbstractModal.jsx [hunk 1]
```diff
@@ -154,7 +154,7 @@ class AbstractModal extends React.Component {
     }
 
     setTimeout(() => {
-      if (this.state.modalTrigger) {
+      if (this.state.modalTrigger && this.state.modalTrigger.focus) {
```
Comment (nramamurth) [inline packages/terra-abstract-modal/src/AbstractModal.jsx]: This is quite similar to https://github.com/davidtheclark/focus-trap-react/pull/19
