### PR TITLE
[terra-tabs, terra-menu] copy classnames for menu icon on clone

### LINKED ISSUE #1599: [terra-menu-item] classnames not copied when cloning icon
# Bug Report

## Description
The terra-menu now allows icons to be placed in the menu.  This includes any icons, in particular, the themeable icons.  However, if any styling is applied to the icon via classnames, those styles will not get carried forward.

## Steps to Reproduce
1.  Create a terra-menu with menu-items that contain icons with icons that can be themed
2.  Apply a classname to the icon that will apply styling to it
3.  Run test and verify in the menu that the classname styling is not applied
4.  Can verify that the classname is missing in the inspector

## Additional Context / Screenshots
Required icon (asterisk) is missing classname styling to make it rec

## Expected Behavior
Expected behavior is to carry forward the classname styling and apply the red coloring
default_icon

## Possible Solution
When cloning the icon in the MenuItem.jsx, append the start-icon styling to any existing classnames.

## Environment
This can be found in any environment

## @ Mentions
@neilpfeiffer @supreethmr @BenBoersma

### PR DESCRIPTION
**Pull request by kschuste**
### Summary
The terra-menu now allows icons to be placed in the menu. This includes any icons, in particular, the themeable icons. However, if any styling is applied to the icon via classnames, those styles will not get carried forward.  When cloning the icon in the MenuItem.jsx, this will now append the start-icon styling to any existing classnames.

Closes #1599

### Deployment Link

https://terra-framework-deployed-pr-#.herokuapp.com/

### Testing
This has been tested locally via the dev-site

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Comment by JessieRandle** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please include a CHANGELOG entry for each changed package this PR. Looks like a CHANGELOG is missing for: 

 - terra-framework-docs
 - terra-tabs</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1a3dade9bb476f4596db926289da2b57c91761e4
</p>

**Comment by JessieRandle** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please include a CHANGELOG entry for each changed package this PR. Looks like a CHANGELOG is missing for: 

 - terra-tabs</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6e6147dc701675158978a05483b810ba584d3639
</p>

**Comment by JessieRandle** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please include a CHANGELOG entry for each changed package this PR. Looks like a CHANGELOG is missing for: 

 - terra-application-navigation
 - terra-application-utility
 - terra-collapsible-menu-view
 - terra-date-picker
 - terra-date-time-picker
 - terra-dialog-modal
 - terra-navigation-side-menu
 - terra-notification-dialog
 - terra-popup</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 768a03a87ae0db5ca038a3b3e0ec403f7bb588e9
</p>

**Comment by supreethmr** [comment]
Can you update the PR to have only fix for #1603  and remove the jest updates added to fix the build ?? we will create different PR for snapshot update so that we can do quick review on that and get it merged to fix the travis build.

**Comment by kschuste** [comment]
> Can you update the PR to have only fix for #1603 and remove the jest updates added to fix the build ?? we will create different PR for snapshot update so that we can do quick review on that and get it merged to fix the travis build.

@supreethmr I reverted those changes, now it just contains the changes I made for terra-menu only

**Review by BenBoersma — APPROVED** [review]

File: packages/terra-menu/src/MenuItem.jsx [hunk 1]
```diff
@@ -281,12 +281,12 @@ class MenuItem extends React.Component {
         fitStartIcon = <InstructionsForUseIcon className={cx('start-icon')} />;
       } else if (toggleableMenu) {
         if (!toggleable && icon) {
-          fitStartIcon = React.cloneElement(icon, { className: cx('start-icon') });
+          fitStartIcon = React.cloneElement(icon, { className: `${icon.props.className} ${cx('start-icon')}` });
```
Comment (supreethmr) [inline packages/terra-menu/src/MenuItem.jsx:284]: Can we have this classes declared outside if block and re-use it where-ever required.
```js
const iconClass = cx([icon.props.className, 'start-icon']);
```
```suggestion
          fitStartIcon = React.cloneElement(icon, { className: iconClass });
```

**Review by supreethmr — CHANGES_REQUESTED** [review]
+1 with comments addressed

File: packages/terra-menu/src/MenuItem.jsx (hunk 1 above)
Comment (kschuste) [reply packages/terra-menu/src/MenuItem.jsx:284]: @supreethmr I don't see a good way to accommodate this as the icon may be null outside of where I am appending the classname.  The icon may be null is some cases, therefore, I will always need to have an if check for it, also, in the case of I have an icon and the menu is toggleable, I have an icon given, but we apply the checkmark; therefore, no icon styles are needed but need checkmark classnames.  If I moved the icon classnames out, then I would expect to move the checkmark classnames out as well for when the menu is toggleable or when I need to reserve space.

Therefore, if I moved the declaration of these classes out, I would need to repeat this same if block twice
I feel is is much more clear and much less code to apply it right when the icon is cloned as it is being done currently for the icon and the other start icons already.

Comment (supreethmr) [reply packages/terra-menu/src/MenuItem.jsx:284]: I think you got it wrong. Let me put it in this way 

This is your code 
```js
        if (!toggleable && icon) {
          fitStartIcon = React.cloneElement(icon, { className: `${icon.props.className} ${cx('start-icon')}` });
        } else {
          fitStartIcon = <CheckIcon className={cx(['checkmark', 'start-icon'])} />;
        }
      } else if (icon) {
        fitStartIcon = React.cloneElement(icon, { className: `${icon.props.className} ${cx('start-icon')}` });
      }
```

Nit: my suggestion was to just take out string concat 
```js
        if (!toggleable && icon) {
          fitStartIcon = React.cloneElement(icon, { className: cx([icon.props.className, 'start-icon']) });
        } else {
          fitStartIcon = <CheckIcon className={cx(['checkmark', 'start-icon'])} />;
        }
      } else if (icon) {
        fitStartIcon = React.cloneElement(icon, { className: cx([icon.props.className, 'start-icon']) });
      }
```
I don't think this would additional if else !!

**Review by supreethmr — APPROVED** [review]

File: packages/terra-menu/src/MenuItem.jsx (hunk 1 above)
Comment (kschuste) [reply packages/terra-menu/src/MenuItem.jsx]: gotcha!  thanks @supreethmr 
I have now updated to match the above

**Comment by JessieRandle** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please include a CHANGELOG entry for each changed package this PR. Looks like a CHANGELOG is missing for: 

 - terra-collapsible-menu-view
 - terra-tabs</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 72d0ff4e0dff3f87ca4255bb89c439292dbd532d
</p>

**Review by neilpfeiffer — APPROVED** [review]
Tested: PR #1600 (Contribution)

\
\
**Reviewed:**
- Correctly clones classNames applied to icons when used in terra-menu.
- Works in all states and situations including disabled menu-items.
- Shows test example for custom menu-icon color with theming.
- Corrects other menu-item icon color state mistakes in all themes.
- Corrects incorrect focus glow showing on base menu lists.


**UX Reviewed** |
-----------|
