### PR TITLE
[terra-menu] Fix keyboard (up/down arrow) and mouse-click navigation …

### LINKED ISSUE #801: [terra-menu] Arrow key focus is broken for menu item groups
# Bug Report

## Description
Arrow key focus breaks when cycling through a menu item group to get to other menu items.

### Down arrow
1. https://engineering.cerner.com/terra-framework/#/raw/tests/terra-menu/menu/menu/large-menu
2. Use the down arrow key to cycle focus
3. Focus jumps from the first menu item group item (Default 61) back to first menu item (Default 1).

### Up arrow
1. https://engineering.cerner.com/terra-framework/#/raw/tests/terra-menu/menu/menu/large-menu
2. Use the up arrow key to cycle focus
3. Focus toggles between last menu item group item (Default 153) and last menu item (Default 16).

test_optimized

### PR DESCRIPTION
**Pull request by nramamurth**
…amongst the Menu Items within a Group.

Fixes #801 

Deployment Link
https://terra-framework-deploye-pr-806.herokuapp.com/components/terra-menu/menu/menu
and
https://terra-framework-deploye-pr-806.herokuapp.com/tests/terra-menu/menu/menu/large-menu

### CODE REVIEW

File: packages/terra-menu/src/MenuItemGroup.jsx [hunk 1]
```diff
@@ -58,8 +58,8 @@ class MenuItemGroup extends React.Component {
       return React.cloneElement(child, {
         isSelectable,
         isSelected: this.state.selectedIndex === index,
-        onClick: Utils.wrappedOnClickForItem(child.props.onKeyDown, this.handleItemSelection, { index }),
-        onKeyDown: Utils.wrappedOnKeyDownForItem(child.props.onClick, this.handleItemSelection, { index }),
+        onClick: Utils.wrappedOnClickForItem(child.props.onClick, this.handleItemSelection, { index }),
```
Comment (nramamurth) [inline packages/terra-menu/src/MenuItemGroup.jsx]: 👀

**Comment by mmalaker** [comment]
Functional verification completed. The examples now display and function as expected with tab and arrow key navigation; however, during screen reader testing, I found an issue with desktop VoiceOver and JAWS. Screen reader navigation allows focus to shift out of the popup while it is still open. I've logged issue #833 for that.
