### PR TITLE
[terra-time-input] Remove placeholder

### LINKED ISSUE #1193: Remove placeholders
# Bug Report

## Description
The contrast of the color of placeholders with their background does not meet the minimum color contrast ratio of 4.5:1. Darkening the placeholder color increases the risk of making it appear as actual entered value. For this reason, placeholders in `terra-date-input`, `terra-date-picker`, `terra-time-input` should be removed and replaced with help text. 

[Comment](https://github.com/cerner/terra-core/issues/2992#issuecomment-651124550) originally from https://github.com/cerner/terra-core/issues/2992 was moved to this issue for guidance: 
See https://github.com/cerner/terra-framework/issues/1193#issuecomment-660363635

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by pranav300**
### Summary

This PR
Removes placeholder from the input.
Adds format to be displayed under the time-input.

Edit: Removed themeable variable `--terra-time-input-meridiem-button-group-margin-bottom`

Closes #1193

### Deployment Link

https://terra-framew-remove-pla-jmtcda.herokuapp.com/components/terra-time-input/time-input/time-input

### Additional Details

Time Input:
Screenshot 2020-09-10 at 5 49 16 PM

12-hour
Screenshot 2020-09-10 at 5 49 31 PM
 time input:

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Review by emilyrohrbough — COMMENTED** [review]
Should these tests be updated to test accessibility now as well? https://github.com/cerner/terra-framework/blob/main/packages/terra-time-input/tests/wdio/time-input-twelve-hour-spec.js#L5

File: packages/terra-time-input/src/TimeInput.jsx [hunk 1]
```diff
@@ -825,6 +831,9 @@ class TimeInput extends React.Component {
             />
           </ButtonGroup>
         )}
+        <div id={formatDescriptionId} className={cx('format-text')} aria-label={`Time Format: ${format}`}>
+          {format}
+        </div>
```
Comment (emilyrohrbough) [inline packages/terra-time-input/src/TimeInput.jsx:836]: Should this be included in the help text or was it meant to be placed under the input? This could cause quite a bit of shifting on a page since this height is increased. Could we end up with alignment issues?

File: packages/terra-time-input/src/TimeInput.jsx [hunk 2]
```diff
@@ -825,6 +831,9 @@ class TimeInput extends React.Component {
             />
           </ButtonGroup>
         )}
+        <div id={formatDescriptionId} className={cx('format-text')} aria-label={`Time Format: ${format}`}>
```
Comment (benbcai) [inline packages/terra-time-input/src/TimeInput.jsx:834]: "Time Format:" should probably be translated.

Comment (pranav300) [reply packages/terra-time-input/src/TimeInput.jsx:834]: Raised jira for translations.

File: packages/terra-time-input/src/TimeInput.jsx (hunk 1 above)
Comment (pranav300) [reply packages/terra-time-input/src/TimeInput.jsx:834]: I don't think that the misalignment we talked about will happen with this until another wrapper is placed over it with the property `display: inline-block`

File: packages/terra-time-input/src/TimeInput.jsx [hunk 3]
```diff
@@ -722,11 +722,17 @@ class TimeInput extends React.Component {
       { 'initial-focus': this.state.secondInitialFocused },
     ]);
 
+    const formatDescriptionId = `terra-time-input-description-format-${uuidv4()}`;
```
Comment (benbcai) [inline packages/terra-time-input/src/TimeInput.jsx:725]: `formatDescriptionId` changes on every render with the way it is. Perhaps wrap uuidv2 with `useRef`.

```suggestion
    const formatDescriptionId = `terra-time-input-description-format-${useRef(uuidv4())}`;
```

**Review by benbcai — APPROVED** [review]

**Review by lokesh-0813 — APPROVED** [review]

**Comment by neilpfeiffer** [comment]
Tested: PR #1235
Part 2 of 3 for issue #1193

**Reviewed:**
- Removes placeholders - Add Date Format Mask as description text below TimeInput

 \
\
**Fix with Followup Issues:**
- Enhancement: #1246 - Add TimeInputField subcomponent 
- Enhancement: [_add issue #_] Enhance keyboard navigation, today/now shortcut, focus styling  
- Enhancement: [_add issue #_] Enhance accessibility to announce the output when full date value is selected 

\
\
Verified by @neilpfeiffer, Ready to Merge

**Pass** |
-----------|
UX Review|

**Review by ryanthemanuel — APPROVED** [review]

**Comment by pranav300** [comment]
> Should these tests be updated to test accessibility now as well? https://github.com/cerner/terra-framework/blob/main/packages/terra-time-input/tests/wdio/time-input-twelve-hour-spec.js#L5

Yes, updated the tests here https://github.com/cerner/terra-framework/pull/1235/commits/df91b795a6bb0aaddb26f731b6723e62e74be4d5
