### PR TITLE
[terra-application-navigation] Focus to be returned correctly.

### LINKED ISSUE #1120: Focus not properly returned after navigation prompt on primary navigation item.
# Bug Report
## Description
Focus not properly returned after navigation prompt on primary navigation item.
Instead of returning focus to the selected item, focus is returned to root.

## Steps to Reproduce
1.  Navigate to: http://engineering.cerner.com/terra-application/raw/tests/terra-application/application-navigation/application-navigation-test
2. Enable the pending action.
3. Select Page 2 primary navigation item
4. Reject the navigation prompt (continue editing)

Expected: Focus is returned to primary navigation item 2.
Actual: Focus is returned to root.

This can be demonstrated by pressing tab after step 4.

## Additional Context / Screenshots
Also technically when accepting a navigation prop on a primary navigation item, focus should be sent to main, not returned to the primary navigation item.

## Expected Behavior
Expected: Focus is returned to primary navigation item 2.
Actual: Focus is returned to root.

## Environment
* Component Name and Version: terra-application
* Browser Name and Version: Chrome latest
* Node/npm Version: un-related
* Webpack Version: un-related
* Operating System and version (desktop or mobile):

## @ Mentions
@tbiethman

### PR DESCRIPTION
**Pull request by pranav300**
### Summary

Closes #1120 

### Deployment Link

https://terra-framework-deployed-pr-#.herokuapp.com/

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: packages/terra-application-navigation/src/ApplicationNavigation.jsx [hunk 1]
```diff
@@ -328,6 +320,16 @@ const ApplicationNavigation = ({
       closeMenuCallbackRef.current = undefined;
     }
   });
+  
+  useLayoutEffect(() => {
+    if (activeNavigationItemKey !== renderedNavItemKeyRef.current) {
+      setTimeout(() => {
+        focusMainContent();
+      }, 0);
```
Comment (tbiethman) [inline packages/terra-application-navigation/src/ApplicationNavigation.jsx:328]: The timeout is necessary due to the AbstractModal's similar focus logic: https://github.com/cerner/terra-framework/blob/master/packages/terra-abstract-modal/src/inertHelpers.js#L56

Without the timeout, this executes too quickly.

File: packages/terra-application-navigation/CHANGELOG.md [hunk 2]
```diff
@@ -3,6 +3,9 @@ Changelog
 
 Unreleased
 ----------
+### Fixed
+* Focus should be returned to latest selected key when navigation prompt is dismissed.
+* Focus should be passed to `Content` when navigation prompt is accepted.
```
Comment (ShettyAkarsh) [inline packages/terra-application-navigation/CHANGELOG.md:8]: Update here :- Navigation prompt is accepted and Tab key is pressed

Comment (pranav300) [reply packages/terra-application-navigation/CHANGELOG.md]: Updated here https://github.com/cerner/terra-framework/pull/1124/commits/a5857599a27987dc48f9fa5061aebbdc3d8d658d.

File: packages/terra-application-navigation/src/ApplicationNavigation.jsx (hunk 1 above)
Comment (mjhenkes) [reply packages/terra-application-navigation/src/ApplicationNavigation.jsx:329]: Add a comment to the code, I could see this getting 'cleaned up'.

**Comment by PaulSolDev** [comment]
Functional review complete. No issues identified.

File: packages/terra-application-navigation/src/ApplicationNavigation.jsx [hunk 3]
```diff
@@ -171,6 +172,7 @@ const ApplicationNavigation = ({
     };
   }
 
+  // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (mjhenkes) [inline packages/terra-application-navigation/src/ApplicationNavigation.jsx:175]: Why did this need to be added when the line below hasn't changed?

**Comment by neilpfeiffer** [comment]
UX +1

Suggestion to add additional wdio tests for a Reject action from the navigation prompt checkpoint.

File: packages/terra-application-navigation/src/ApplicationNavigation.jsx (hunk 3 above)
Comment (pranav300) [reply packages/terra-application-navigation/src/ApplicationNavigation.jsx:175]: I had added that because of function `focusMainContent` throwing lint warning:
`The 'focusMainContent' function makes the dependencies of useLayoutEffect Hook`.

I can update it in a later PR with `useCallback` hook.
