### PR TITLE
[terra-date-picker] Clear out selected date if invalid date is entered after a valid date.

### LINKED ISSUE #1185: Date picker is not displaying correct year on invalid date
# Bug Report

## Description
If you enter date manually in date picker (10/10/1990) and click on the calendar Icon it displays 10 date and 10 month but it will display current year.

## Steps to Reproduce
1. Manually enter date that is in past year (10/10/2019)
2.Click on calendar Icon.

## Additional Context / Screenshots
Screen Shot 2020-07-10 at 11 07 10 PM

## Expected Behavior
Expecting to see year as entered in date field. for example if this date (10/10/2019) is entered expecting to see 2019 in calendar display

## Environment

* Component Name and Version: Terra-date-picker (4.40.0)
* Browser Name and Version: chrome (83.0.4103.116)
* Node/npm Version: 11.0.0/6.13.7
* Webpack Version: 4.41.2
* Operating System and version (desktop or mobile): mac os

### PR DESCRIPTION
**Pull request by saket2403**
### Summary
Clear out the selected date on each keypress in `onChangeRaw` function if an invalid date is entered after a valid one.
Closes #1185 

### Deployment Link

[Link](https://terra-framew-date-picke-0kmbuf.herokuapp.com/components/terra-date-picker/date-picker/date-picker)

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: packages/terra-date-picker/src/terra-dev-site/doc/example/DatePickerDefault.jsx [hunk 1]
```diff
@@ -23,12 +23,19 @@ class DatePickerExample extends React.Component {
...
+    this.handleDateChangeRaw = this.handleDateChangeRaw.bind(this);
   }
 
   handleDateChange(event, date) {
     this.setState({ date });
   }
 
+  handleDateChangeRaw(event, date, metadata) {
+    if (!metadata.isValidValue) {
+      this.setState({ date: null });
```
Comment (benbcai) [inline packages/terra-date-picker/src/terra-dev-site/doc/example/DatePickerDefault.jsx:35]: nit: It would be nice to change all of these to use the useState hook.

**Comment by PaulSolDev** [comment]
Functional review complete. No issues identified.
