### PR TITLE
[terra-tabs]Fixed lowlight and clinical theme interference.

### LINKED ISSUE #1092: [terra-tabs] Application w/clinical theme and clinical-lowlight-theme interfere
# Bug Report
We have been using a component that activates the clinical lowlight theme when it is mounted as it is intended to be used within an imaging environment. We embed this component in a regular clinical application that uses the clinical theme and previously the theme would activate/deactivate without issue. It now seems that with the latest terra-tabs and clinical lowlight theme there is bleed through between the clinical theme and the clinical lowlight theme for the tab backgrounds:

## Steps to Reproduce
Create an application with the clinical theme applied
Create a child component that later activates the lowlight theme

## Additional Context / Screenshots
Screen Shot 2020-04-09 at 1 43 16 PM

## Expected Behavior
I would expect the tabs to render as they normally do with the lowlight theme applied

## Possible Solution
Fill out all theme properties for the themed components.

## Environment

* Component Name and Version: terra-tabs 6.32
* Browser Name and Version: Chrome 
* Node/npm Version: node 10
* Webpack Version: 4
* Operating System and version (desktop or mobile): macOS Catalina

## @ Mentions
@mjhenkes

### PR DESCRIPTION
**Pull request by saket2403**
### Summary
Applied theme context and back filled missing theme variables in  lowlight theme.
Closes #1092 

### Deployment Link

https://terra-framework-deployed-pr-#.herokuapp.com/

### Testing
Added jest tests to verify theme class application .

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: packages/terra-tabs/src/TabPane.jsx [hunk 1]
```diff
@@ -75,7 +78,7 @@ const TabPane = ({
     <div {...attributes} role="tab" className={paneClassNames}>
       {customDisplay}
       {customDisplay ? null : icon}
-      {customDisplay || isIconOnly ? null : <span className={cx('label')}>{label}</span>}
+      {customDisplay || isIconOnly ? null : <span className={classNames(cx('label'), theme.classNames)}>{label}</span>}
```
Comment (emilyrohrbough) [inline packages/terra-tabs/src/TabPane.jsx:81]:
```suggestion
      {customDisplay || isIconOnly ? null : <span className={cx('label')}>{label}</span>}
```

File: packages/terra-tabs/src/Tabs.module.scss [hunk 2]
```diff
@@ -1,5 +1,10 @@
 @import './ModularTabs.module';
 @import './StructuralTabs.module';
+// Themes
+@import './clinical-lowlight-theme/Tabs.module';
+@import './orion-fusion-theme/Tabs.module';
+
+
```
Comment (emilyrohrbough) [inline packages/terra-tabs/src/Tabs.module.scss:8]: extra line need removed

File: packages/terra-tabs/src/TabPane.jsx (hunk 1 above)
Comment (mjhenkes) [inline packages/terra-tabs/src/TabPane.jsx:81]: I think you want the theme class name inside the cx function.
```suggestion
      {customDisplay || isIconOnly ? null : <span className={cx('label', theme.classNames)}>{label}</span>}
```

File: packages/terra-tabs/src/Tabs.jsx [hunk 3]
```diff
@@ -176,7 +181,7 @@ class Tabs extends React.Component {
         isIconOnly = true;
       }
       clonedPanes.push(React.cloneElement(child, {
-        className: cx([{ 'is-active': isActive }, child.props.className]),
+        className: classNames(cx({ 'is-active': isActive }, theme.className), child.props.className),
```
Comment (mjhenkes) [inline packages/terra-tabs/src/Tabs.jsx:184]: theme.classname should be inside the cx function

File: packages/terra-tabs/src/Tabs.jsx [hunk 4]
```diff
@@ -228,7 +233,7 @@ class Tabs extends React.Component {
       >
         <div
           role="tabpanel"
-          className={cx(['pane-content', { 'fill-parent': fill }])}
+          className={classNames(cx('pane-content', { 'fill-parent': fill }, theme.className))}
```
Comment (mjhenkes) [inline packages/terra-tabs/src/Tabs.jsx:236]: Here too.

File: packages/terra-tabs/src/_CollapsedTabs.jsx [hunk 5]
```diff
@@ -26,8 +28,9 @@ const propTypes = {
 
 const CollapsedTabs = (props) => {
   props.onTruncationChange(false);
+  const theme = React.useContext(ThemeContext);
   return (
-    <div className={cx('collapsed-tabs-container')}>
+    <div className={classNames(cx('collapsed-tabs-container', theme.className))}>
```
Comment (mjhenkes) [inline packages/terra-tabs/src/_CollapsedTabs.jsx:33]: theme.classname should be inside the cx function

File: packages/terra-tabs/src/_CollapsibleTabs.jsx [hunk 6]
```diff
@@ -265,13 +268,13 @@ class CollapsibleTabs extends React.Component {
     );
 
     const selectionBar = this.props.variant === 'modular-centered' || this.props.variant === 'modular-left-aligned' ? (
-      <div className={cx('selection-bar')} ref={(node) => { if (node) { this.selectionBar = node; } }} />
+      <div className={classNames(cx('selection-bar', theme.className))} ref={(node) => { if (node) { this.selectionBar = node; } }} />
```
Comment (mjhenkes) [inline packages/terra-tabs/src/_CollapsibleTabs.jsx:271]: theme.classname should be inside the cx function

File: packages/terra-tabs/src/_CollapsibleTabs.jsx [hunk 7]
```diff
@@ -265,13 +268,13 @@ class CollapsibleTabs extends React.Component {
...
     ) : null;
 
     return (
       <div>
         <div
-          className={cx(['collapsible-tabs-container', { 'is-calculating': this.isCalculating }])}
+          className={classNames(cx('collapsible-tabs-container', { 'is-calculating': this.isCalculating }, theme.className))}
```
Comment (mjhenkes) [inline packages/terra-tabs/src/_CollapsibleTabs.jsx:277]: theme.classname should be inside the cx function

File: packages/terra-tabs/src/TabPane.jsx (hunk 1 above)
Comment (saket2403) [reply packages/terra-tabs/src/TabPane.jsx:81]: Should I move theme.className inside cx or remove it as emily suggested above?

File: packages/terra-tabs/src/orion-fusion-theme/Tabs.module.scss [hunk 8]
```diff
@@ -0,0 +1,90 @@
+:local {
+  .orion-fusion-theme {
```
Comment (mjhenkes) [inline packages/terra-tabs/src/orion-fusion-theme/Tabs.module.scss:2]: it seems like there are a lot more lowlight theme variables than fusion theme variables, could you double check that  the fusion theme has all back filled variables too? It also helps (me check this) if the files are formatted the same with variables in the same order.

File: packages/terra-tabs/src/_TabMenu.jsx [hunk 9]
```diff
@@ -113,7 +116,7 @@ class TabMenu extends React.Component {
         ref={this.setTargetRef}
         onClick={this.handleOnClick}
         onKeyDown={this.handleOnKeyDown}
-        className={cx(['tab-menu', { 'is-active': menuActive }])}
+        className={classNames(cx('tab-menu', { 'is-active': menuActive }, theme.className))}
```
Comment (mjhenkes) [inline packages/terra-tabs/src/_TabMenu.jsx:119]: theme.classname should be inside the cx function

File: packages/terra-tabs/src/TabPane.jsx (hunk 1 above)
Comment (mjhenkes) [reply packages/terra-tabs/src/TabPane.jsx:81]: Actually, you probably don't need to add the class here at all since it's added to the top of the component.

File: packages/terra-tabs/src/Tabs.jsx (hunk 3 above)
Comment (mjhenkes) [reply packages/terra-tabs/src/Tabs.jsx:184]: Actually, you probably don't need to add the class here at all since it's added to the top of the component.

File: packages/terra-tabs/src/orion-fusion-theme/Tabs.module.scss (hunk 8 above)
Comment (saket2403) [reply packages/terra-tabs/src/orion-fusion-theme/Tabs.module.scss:2]: Did not add fusion theme styles for Modular tabs because of this [comment](https://github.com/cerner/terra-framework/blob/c66d1bcc63ef184bf4fd589f0dca9c3b83d240d6/packages/terra-tabs/src/Tabs.jsx#L15).Whether the variant will stay or be removed , also there was no example to verify.

**Comment by saket2403** [comment]
Removed classnames be41bcf

File: packages/terra-tabs/src/orion-fusion-theme/Tabs.module.scss (hunk 8 above)
Comment (mjhenkes) [reply packages/terra-tabs/src/orion-fusion-theme/Tabs.module.scss:2]: If thats the case, why did we add the lowlight variables for modular tabs? I don't think they are use since you cannot set tabs to be a modular variant.

File: packages/terra-tabs/src/_CollapsedTabs.jsx (hunk 5 above)
Comment (mjhenkes) [inline packages/terra-tabs/src/_CollapsedTabs.jsx:33]: You don't need to run this through both classnames and cx if you're not combining local css classes with prop provided css classes
```suggestion
    <div className={cx('collapsed-tabs-container', theme.className)}>
```

File: packages/terra-tabs/src/_CollapsibleTabs.jsx [hunk 10]
```diff
@@ -271,7 +274,7 @@ class CollapsibleTabs extends React.Component {
...
```
Comment (mjhenkes) [inline packages/terra-tabs/src/_CollapsibleTabs.jsx:277]:
```suggestion
          className={cx('collapsible-tabs-container', { 'is-calculating': this.isCalculating }, theme.className)}
```

File: packages/terra-tabs/src/_TabMenu.jsx (hunk 9 above)
Comment (mjhenkes) [inline packages/terra-tabs/src/_TabMenu.jsx:119]:
```suggestion
        className={cx('tab-menu', { 'is-active': menuActive }, theme.className)}
```

File: packages/terra-tabs/src/orion-fusion-theme/Tabs.module.scss (hunk 8 above)
Comment (saket2403) [reply packages/terra-tabs/src/orion-fusion-theme/Tabs.module.scss:2]: Had a talk with neil offline and commented out the modular variant styles in both fusion and lowlight after grouping them

File: packages/terra-tabs/src/clinical-lowlight-theme/Tabs.module.scss [hunk 11]
```diff
@@ -0,0 +1,117 @@
+:local {
+  .clinical-lowlight-theme {
+    --terra-tabs-keyboard-focus-ltr-box-shadow: 0 0 1px 3px #4a90e2, 0 0 7px 4px #4a90e2;
```
Comment (mjhenkes) [inline packages/terra-tabs/src/clinical-lowlight-theme/Tabs.module.scss:3]: note: when the theme variables are organized differently in each theme file, it makes it quite difficult on reviewers to ensure that all theme variables are covered.

File: packages/terra-tabs/src/clinical-lowlight-theme/Tabs.module.scss [hunk 12]
```diff
@@ -0,0 +1,117 @@
...
+    --terra-tabs-structural-disabled-hover-color: #404344;
+    --terra-tabs-structural-disabled-hover-opacity: 1;
+    --terra-tabs-structural-focus-background-image: linear-gradient(to bottom, #141719, #141719);
+    --terra-tabs-structural-last-tab-border-width: 0;
+    --terra-tabs-structural-tab-bar-border-bottom-color: #181b1d;
+    --terra-tabs-structural-tab-bar-border-bottom-width: 1px;
+    --terra-tabs-structural-transition-duration: 0;
+    --terra-tabs-structural-transition-timing-function: ease;
+
+    /* NOTE: This is being commented out until discussions have been resolved around if modular tabs should be removed.
```
Comment (jmsv6d) [inline packages/terra-tabs/src/clinical-lowlight-theme/Tabs.module.scss:87]: We should probably just remove these commented styles for modular tabs. It's unlikely to even be correct at this point.
