### PR TITLE
[terra-application-header-layout] Fixed alignment of the header content.

### LINKED ISSUE #593: Application Header components not aligned
# Bug Report

## Description
The application header contains user information on the right-top corner.
In chrome and IE11 other newer browsers, the title shows properly, but it gets aligned beside the Application layout title.

## Steps to Reproduce

1. Load [terra-application-layout](https://engineering.cerner.com/terra-ui/#/components/terra-application-layout/application-layout/about) in a new browser (Chrome, IE 11, etc.)
2. Remove the navigation items by making it null or empty array.
3. It can be observed that the user name information come to left (gets aligned beside the Application layout title.)

## Additional Context / Screenshots
**Chrome**:
image

**IE11**:
image
## Expected Behavior
User name should get right-aligned
image

## Environment

* Component Name and Version: terra-application-header-layout@4.8.0
* Browser Name and Version: Chrome, IE 11
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version: 3.2.0
* Operating System and version (desktop or mobile): MAC and Windows 10

### PR DESCRIPTION
**Pull request by nramamurth**
### Summary
Fixes #593.

Thanks for contributing to Terra.
@cerner/terra

[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md
[License]: ../blob/master/LICENSE

### CODE REVIEW

File: packages/terra-application-header-layout/tests/wdio/application-header-spec.js [hunk 1]
```diff
@@ -38,4 +38,14 @@ describe('Application Header Layout', () => {
...
     Terra.should.matchScreenshot('Not Visible', { viewports, selector: '#test-header' });
   });
+
+  describe('Displays a application header layout with logo and utilities only', () => {
+    beforeEach(() => {
+      browser.url('/#/raw/tests/terra-application-header-layout/application-header-layout/application-header-with-logo-and-utilities-only');
+      browser.waitForVisible('#test-header');
+    });
+
+    Terra.should.matchScreenshot({ viewports, selector: '#test-header' });
```
Comment (jmsv6d) [inline packages/terra-application-header-layout/tests/wdio/application-header-spec.js]: Should use the new `Terra.should.validateElement()` instead of `Terra.should.matchScreenshot()` and `Terra.should.beAccessible()`

Comment (nramamurth) [reply packages/terra-application-header-layout/tests/wdio/application-header-spec.js]: Done: https://github.com/cerner/terra-framework/pull/604/commits/03196e2e93e12b1783514fcedd11a309475db86a.
