### PR TITLE
Fixes Issue #272 Added role property for Utility Menu

### LINKED ISSUE #272: Terra Utility Menu needs to have the option to switch it's role.
# Bug Report

## Description
The Terra Utility Menu is not always designed to be a navigation component. In our dev site for example, it's used as a menu. To ensure screen readers do not always read this as a navigation menu, we need to allow for the developer to change the value of role. We can default it to "navigation" for passivity purposes.

https://github.com/cerner/terra-framework/blob/01daffb58489853b7663bd406ba0dbd53df96e46/packages/terra-application-utility/src/utility/_UtilityMenu.jsx#L364

### PR DESCRIPTION
**Pull request by supreethmr**
### Summary
Added role property to Utility Menu to allow developer to change the role of Utility menu based on the context it is being used. 

### Additional Details
'Navigation' will remain as default role for Utility Menu.

Resolves #272

### CODE REVIEW

File: packages/terra-application-utility/src/utility/_UtilityMenu.jsx [hunk 1]
```diff
@@ -41,12 +41,20 @@ const propTypes = {
    * This will be provided by the terra-application-header or terra-application-menu.
    */
   onRequestClose: PropTypes.func,
+  /**
+   * Role attribute of Utility Menu.
+   */
+  role: PropTypes.string,
```
Comment (yuderekyu) [inline packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: in my opinion, we should name this `menuRole`, or something more specific.

Comment (supreethmr) [reply packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: I would like to keep this as role since it would be more appropriate as we are referring to Role Attribute of element property name will be more suitable and it will be common across the other components as well. Let me know if there are any other reasons for which we need to change the prop name to menuRole from role.

Comment (supreethmr) [reply packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: Role has been added to Application Menu utility and Application Header Utility and Application Menu Utility and Utility Button.

Comment (yuderekyu) [reply packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: My issue is that it is not clear which component we can set `role` for - a consumer needs to read the description to know they are setting `role` for UtilityMenu. Utility is tricky because it contains many sub components. Does `role` mean a consumer can set the role for the UtilityButton/UtilityMenu/UtilityDivider?

Comment (supreethmr) [reply packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: hmm I missed that, yes it makes sense to keep prop name as menu role as it will be more specific to utility menu role. Changed prop name from role to menuRole.

File: packages/terra-application-utility/CHANGELOG.md [hunk 2]
```diff
@@ -3,6 +3,9 @@ Changelog
 
 Unreleased
 ----------
+### Added
+* Role property added to utility menu
```
Comment (emilyrohrbough) [inline packages/terra-application-utility/CHANGELOG.md]: whoops, lets update this to be menuRole

File: packages/terra-application-utility/src/utility/_UtilityMenu.jsx [hunk 3]
```diff
@@ -367,7 +376,7 @@ class UtilityMenu extends React.Component {
           footer={footer}
           fill={isHeightBounded}
           className={menuClassNames}
-          role="navigation"
+          role={menuRole}
```
Comment (bjankord) [inline packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: I think this makes more sense to move this role to `UL` element that wraps the menu items. Left more detailed info about this on the GitHub issue: https://github.com/cerner/terra-framework/issues/272#issuecomment-462487936

File: packages/terra-application-utility/CHANGELOG.md (hunk 2 above)
Comment (supreethmr) [reply packages/terra-application-utility/CHANGELOG.md]: [Updated](https://github.com/cerner/terra-framework/pull/501/commits/36eb776f7973f67fd6cda910594a53aaadcaf71f)

File: packages/terra-application-utility/src/utility/_UtilityMenu.jsx (hunk 3 above)
Comment (supreethmr) [reply packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: [added role="menu"](https://github.com/cerner/terra-framework/pull/501/commits/36eb776f7973f67fd6cda910594a53aaadcaf71f) to utility-menu-body ul tag as discussed with @JakeLaCombe

Comment (bjankord) [reply packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: It looks like aXe tool we use is now throwing warnings about the addition of role="menu". We probably need to dig into this some and figure out another option. I don't have any thoughts on what change is needed currently but will try and post back on this PR when I get some time to dig into this some more.

Comment (bjankord) [reply packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: Looks like you got this resolves @supreethmr, nice work!

File: packages/terra-application-utility/src/ApplicationHeaderUtility.jsx [hunk 4]
```diff
@@ -30,6 +30,10 @@ const propTypes = {
    * The accessory element to be displayed next to the title.
    */
   accessory: PropTypes.element,
+  /**
+   * Role attribute on the Application Header Utility.
```
Comment (yuderekyu) [inline packages/terra-application-utility/src/ApplicationHeaderUtility.jsx]: Can we change this to 
```suggestion
   * The role attribute to set on the menu.
```

File: packages/terra-application-utility/src/ApplicationMenuUtility.jsx [hunk 5]
```diff
@@ -30,6 +30,10 @@ const propTypes = {
    * The accessory element to be displayed next to the title.
    */
   accessory: PropTypes.element,
+  /**
+   * Role attribute on the Application Menu.
```
Comment (yuderekyu) [inline packages/terra-application-utility/src/ApplicationMenuUtility.jsx]: Can we change this to 
```suggestion
   * The role attribute to set on the menu.
```

File: packages/terra-application-utility/src/utility/_UtilityButton.jsx [hunk 6]
```diff
@@ -41,6 +41,10 @@ const propTypes = {
    * The image associated with utilities.
    */
   accessory: PropTypes.element,
+  /**
+   * Role attribute of Utlity Menu.
```
Comment (yuderekyu) [inline packages/terra-application-utility/src/utility/_UtilityButton.jsx]: Can we change this to 
```suggestion
   * The role attribute to set on the menu.
```

File: packages/terra-application-utility/src/ApplicationHeaderUtility.jsx (hunk 4 above)
Comment (supreethmr) [reply packages/terra-application-utility/src/ApplicationHeaderUtility.jsx]: [updated the doc](https://github.com/cerner/terra-framework/pull/501/commits/95bc33f8a3c45d78146c62cb9d9add2de6f13b71)

File: packages/terra-application-utility/src/utility/_UtilityMenu.jsx (hunk 3 above)
Comment (supreethmr) [reply packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: thank you. :)

File: packages/terra-application-utility/src/utility/_UtilityButton.jsx (hunk 6 above)
Comment (supreethmr) [reply packages/terra-application-utility/src/utility/_UtilityButton.jsx]: sure updated in all the above mentioned [places](https://github.com/cerner/terra-framework/pull/501/commits/95bc33f8a3c45d78146c62cb9d9add2de6f13b71).

File: packages/terra-application-utility/src/ApplicationMenuUtility.jsx (hunk 5 above)
Comment (supreethmr) [reply packages/terra-application-utility/src/ApplicationMenuUtility.jsx]: :thumbsup: [updated](https://github.com/cerner/terra-framework/pull/501/commits/95bc33f8a3c45d78146c62cb9d9add2de6f13b71)​​​​​​​​​​​​​
​​​​​​​

File: packages/terra-application-utility/src/utility/_UtilityMenu.jsx (hunk 3 above)
Comment (supreethmr) [reply packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: thank you..!

**Comment by supreethmr** [comment]
Class name and Const Names like Utility Button and ApplicationMenuUtility has been named as ApplicationHeaderUtility : [here](https://github.com/cerner/terra-framework/blob/67d3deb6af953927cc9d254fd350de603e212afd/packages/terra-application-utility/src/ApplicationMenuUtility.jsx#L39) and UtilityButton named as ApplicationHeaderUtility : [here](https://github.com/cerner/terra-framework/blob/67d3deb6af953927cc9d254fd350de603e212afd/packages/terra-application-utility/src/utility/_UtilityButton.jsx#L58) Is this the intended code or do we need to rename it to UtilityButton and ApplicationMenuUtility.

**Comment by yuderekyu** [comment]
@supreethmr oops, those are misnamed - let's update them to `UtilityButton` and `ApplicationMenuUtility`. Nice find!

File: packages/terra-application-utility/src/ApplicationHeaderUtility.jsx [hunk 7]
```diff
@@ -49,6 +54,7 @@ const ApplicationHeaderUtility = ({
     initialSelectedKey={initialSelectedKey}
     title={title}
     accessory={accessory}
+    role={menuRole}
```
Comment (yuderekyu) [inline packages/terra-application-utility/src/ApplicationHeaderUtility.jsx]:
```suggestion
    menuRole={menuRole}
```

File: packages/terra-application-utility/src/ApplicationMenuUtility.jsx [hunk 8]
```diff
@@ -49,6 +54,7 @@ const ApplicationHeaderUtility = ({
     initialSelectedKey={initialSelectedKey}
     title={title}
     accessory={accessory}
+    role={menuRole}
```
Comment (yuderekyu) [inline packages/terra-application-utility/src/ApplicationMenuUtility.jsx]:
```suggestion
    menuRole={menuRole}
```

File: packages/terra-application-utility/tests/jest/UtilityMenu.test.jsx [hunk 9]
```diff
@@ -100,4 +100,42 @@ describe('UtilityMenu', () => {
...
+    const role = 'menu';
+    const component = (
+      <IntlProvider locale={locale} messages={messages}>
+        <HeaderUtilityMenu
+          initialSelectedKey="key"
+          menuItems={config}
+          onChange={mockOnChange}
+          onDisclose={mockOnDisclose}
+          variant={variant}
+          role={role}
```
Comment (yuderekyu) [inline packages/terra-application-utility/tests/jest/UtilityMenu.test.jsx]:
```suggestion
          menuRole={role}
```

File: packages/terra-application-utility/tests/jest/UtilityMenu.test.jsx [hunk 10]
```diff
@@ -100,4 +100,42 @@ describe('UtilityMenu', () => {
...
+    const defaultRole = 'navigation';
+    const component = (
+      <IntlProvider locale={locale} messages={messages}>
+        <HeaderUtilityMenu
+          initialSelectedKey="key"
+          menuItems={config}
+          onChange={mockOnChange}
+          onDisclose={mockOnDisclose}
+          variant={variant}
+          role={defaultRole}
```
Comment (yuderekyu) [inline packages/terra-application-utility/tests/jest/UtilityMenu.test.jsx]:
```suggestion
          menuRole={defaultRole}
```

File: packages/terra-application-utility/src/ApplicationHeaderUtility.jsx (hunk 7 above)
Comment (supreethmr) [reply packages/terra-application-utility/src/ApplicationHeaderUtility.jsx]: [Changed to menurole](https://github.com/cerner/terra-framework/pull/501/commits/131aaf225ec1730dafcfecf63f4d79d0857c6bfa)

File: packages/terra-application-utility/src/ApplicationMenuUtility.jsx (hunk 8 above)
Comment (supreethmr) [reply packages/terra-application-utility/src/ApplicationMenuUtility.jsx]: [Changed to menurole](https://github.com/cerner/terra-framework/pull/501/commits/131aaf225ec1730dafcfecf63f4d79d0857c6bfa)

File: packages/terra-application-utility/tests/jest/UtilityMenu.test.jsx (hunk 9 above)
Comment (supreethmr) [reply packages/terra-application-utility/tests/jest/UtilityMenu.test.jsx]: [Changed to menurole](https://github.com/cerner/terra-framework/pull/501/commits/131aaf225ec1730dafcfecf63f4d79d0857c6bfa)

File: packages/terra-application-utility/tests/jest/UtilityMenu.test.jsx (hunk 10 above)
Comment (supreethmr) [reply packages/terra-application-utility/tests/jest/UtilityMenu.test.jsx]: [Changed to menurole](https://github.com/cerner/terra-framework/pull/501/commits/131aaf225ec1730dafcfecf63f4d79d0857c6bfa)

File: packages/terra-application-utility/src/ApplicationHeaderUtility.jsx (hunk 7 above)
Comment (yuderekyu) [reply packages/terra-application-utility/src/ApplicationHeaderUtility.jsx]: update to camelCase - `menuRole`

File: packages/terra-application-utility/src/ApplicationMenuUtility.jsx (hunk 8 above)
Comment (yuderekyu) [reply packages/terra-application-utility/src/ApplicationMenuUtility.jsx]: update to camelCase - `menuRole`

File: packages/terra-application-utility/tests/jest/UtilityMenu.test.jsx (hunk 9 above)
Comment (yuderekyu) [reply packages/terra-application-utility/tests/jest/UtilityMenu.test.jsx]: update to camelCase - `menuRole`

File: packages/terra-application-utility/tests/jest/UtilityMenu.test.jsx (hunk 10 above)
Comment (yuderekyu) [reply packages/terra-application-utility/tests/jest/UtilityMenu.test.jsx]: update to camelCase - `menuRole`

Comment (supreethmr) [reply packages/terra-application-utility/tests/jest/UtilityMenu.test.jsx]: When I update this to camel case It throws warning saying : 
screen shot 2019-03-01 at 8 44 10 pm

File: packages/terra-application-utility/src/utility/_UtilityMenu.jsx [hunk 11]
```diff
@@ -41,6 +41,11 @@ const propTypes = {
    * This will be provided by the terra-application-header or terra-application-menu.
    */
   onRequestClose: PropTypes.func,
+  /**
+   *
+   * The role attribute of Utility Menu.
+   */
+  menurole: PropTypes.string,
```
Comment (yuderekyu) [inline packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: change this to `menuRole` in order for the jest test to pass
```suggestion
  menuRole: PropTypes.string,
```

Comment (supreethmr) [reply packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: [propName has been changed to camelcase](https://github.com/cerner/terra-framework/pull/501/commits/8e717f363590ac70e52d300484c4a414037191d9) in all places except for utility button since react does not recognize the prop with camel case on DOM Element

File: packages/terra-application-layout/tests/jest/__snapshots__/ApplicationHeader.test.jsx.snap [hunk 12]
```diff
@@ -71,6 +71,7 @@ exports[`ApplicationHeader should render props 1`] = `
             },
           ]
         }
+        menurole="Navigation"
```
Comment (yuderekyu) [inline packages/terra-application-layout/tests/jest/__snapshots__/ApplicationHeader.test.jsx.snap]: regenerated this snapshot to contain `menuRole`, instead of `menurole`

File: packages/terra-application-utility/src/utility/_UtilityMenu.jsx (hunk 11 above)
Comment (yuderekyu) [reply packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: What's the error React throws? UtilityButton renders the UtilityMenu, not a native DOM element - I'd think we'd be fine passing that prop

Comment (supreethmr) [reply packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: it throws below warning when I change prop on utility button to menuRole : screen shot 2019-03-04 at 9 54 17 pm .

File: packages/terra-application-utility/src/utility/_UtilityButton.jsx [hunk 13]
```diff
@@ -135,7 +140,7 @@ class ApplicationHeaderUtility extends React.Component {
   }
```
Comment (yuderekyu) [inline packages/terra-application-utility/src/utility/_UtilityButton.jsx]: on line 96, create a new line and add `menuRole`.

File: packages/terra-application-utility/src/utility/_UtilityMenu.jsx (hunk 11 above)
Comment (yuderekyu) [reply packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: We need to destructure the `menuRole` prop from `this.props`. I added a comment on UtilityButton. Make that change and change `menurole` to `menuRole` for the higher order components - does this resolve the issue?

Comment (bjankord) [reply packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: It looks like we spread all custom props onto the utility button resulting in `menuRole` being applied as a prop / attribute on the DOM element. We likely need some logic to delete menuRole out of custom props so it is not added to the DOM element.

It looks like in `packages/terra-application-utility/src/utility/_UtilityButton.jsx` on line 101, we `delete customProps.onClick`. We should test doing the same thing for menuRole on line 102.
Add the following:
`delete customProps.menuRole;`

Comment (supreethmr) [reply packages/terra-application-utility/src/utility/_UtilityMenu.jsx]: this worked..! thanks for suggestion @bjankord [prop has been renamed to camel case](8bb27390433900a5998d80ec415a7d74b3e59624)

File: packages/terra-application-utility/src/utility/_UtilityButton.jsx (hunk 13 above)
Comment (bjankord) [reply packages/terra-application-utility/src/utility/_UtilityButton.jsx]: I think that may lead to a lint error as we'd destructure menuRole and I think the linter would complain about menuRole being defined but never used, not 100% sure though.

Comment (yuderekyu) [reply packages/terra-application-utility/src/utility/_UtilityButton.jsx]: ye, your suggestion of deleting the prop makes more sense 👍
