### PR TITLE
[terra-date-picker, terra-date-time-picker] Deprecate prop onClickOutside

### LINKED ISSUE #1219: [terra-date-time-picker] onClickOutside callback event does not get triggered
# Bug Report

## Description

`onClickOutside` callback event does not get triggered when the calendar dropdown is closed by clicking outside it.

## Steps to Reproduce

1. Goto https://engineering.cerner.com/terra-framework/components/terra-date-time-picker/date-time-picker/events
2. Scroll down to the event example and click on calendar button to open the dropdown calendar.
3. On clicking outside of the calendar dropdown does not trigger onClickOutside event callback and the counter also does not increment.

## Expected Behavior

Clicking outside the calendar dropdown should trigger the onClickOutside callback event.

### PR DESCRIPTION
**Pull request by pranav300**
### Summary

This PR adds a new prop `onDismiss` that will be replace `onClickOutside` in #1222.
Added deprecated label for `onClickOutside`.

Closes #1219 

### Deployment Link

https://terra-framew-deprecate--4rpntg.herokuapp.com/

### Testing

https://terra-framew-deprecate--4rpntg.herokuapp.com/components/terra-date-time-picker/date-time-picker/events

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: packages/terra-date-picker/src/DatePicker.jsx [hunk 1]
```diff
@@ -137,6 +141,7 @@ const defaultProps = {
   onChange: undefined,
   onChangeRaw: undefined,
   onClickOutside: undefined,
+  onDismiss: undefined,
```
Comment (emilyrohrbough) [inline packages/terra-date-picker/src/DatePicker.jsx:144]: this is undefined by default

File: packages/terra-date-picker/src/react-datepicker/index.jsx [hunk 2]
```diff
@@ -195,9 +195,13 @@ class DatePicker extends React.Component {
      */
     onWeekSelect: PropTypes.func,
     /**
-     * A callback function to execute when the mouse cursor leaves the element.
+     * **Deprecated**, A callback function to execute when the mouse cursor leaves the element. Resolves to `onDismiss`.
      */
     onClickOutside: PropTypes.func,
+    /**
+     * A callback function to execute when the mouse cursor leaves the element.
```
Comment (emilyrohrbough) [inline packages/terra-date-picker/src/react-datepicker/index.jsx:202]: Add `onDismiss(event)` so consumers know what parameter(s) will be sent back.

File: packages/terra-date-time-picker/src/DateTimePicker.jsx [hunk 3]
```diff
@@ -3,7 +3,7 @@ import { injectIntl, intlShape } from 'react-intl';
 import PropTypes from 'prop-types';
 import classNames from 'classnames/bind';
 import ThemeContext from 'terra-theme-context';
-import DatePicker from 'terra-date-picker';
+import DatePicker from 'terra-date-picker/src/DatePicker';
```
Comment (emilyrohrbough) [inline packages/terra-date-time-picker/src/DateTimePicker.jsx:6]:
```suggestion
import DatePicker from 'terra-date-picker';
```

File: packages/terra-date-picker/src/DatePicker.jsx [hunk 4]
```diff
@@ -454,6 +460,7 @@ class DatePicker extends React.Component {
             onChange={this.handleChange}
             onChangeRaw={this.handleChangeRaw}
             onClickOutside={this.handleOnClickOutside}
+            onDismiss={onDismiss}
```
Comment (emilyrohrbough) [inline packages/terra-date-picker/src/DatePicker.jsx:463]: onClickOutside should be removed and passed like:
```suggestion
            onDismiss={onDismiss || onClickOutside}
```

File: packages/terra-date-picker/src/react-datepicker/index.jsx [hunk 5]
```diff
@@ -195,9 +195,13 @@ class DatePicker extends React.Component {
      */
     onWeekSelect: PropTypes.func,
     /**
-     * A callback function to execute when the mouse cursor leaves the element.
+     * **Deprecated**, A callback function to execute when the mouse cursor leaves the element. Resolves to `onDismiss`.
```
Comment (emilyrohrbough) [inline packages/terra-date-picker/src/react-datepicker/index.jsx:198]: I'd add a note that onDismiss will be used before onClickOutside if both are provided.

File: packages/terra-date-picker/src/DatePicker.jsx [hunk 6]
```diff
@@ -88,9 +88,13 @@ const propTypes = {
...
   onChangeRaw: PropTypes.func,
   /**
-   * A callback function to execute when clicking outside of the picker to dismiss it.
+   * **Deprecated**, A callback function to execute when clicking outside of the picker to dismiss it. Resolves to `onDismiss`.
    */
   onClickOutside: PropTypes.func,
+  /**
+   * A callback function to execute when clicking outside of the picker to dismiss it.
+   */
+  onDismiss: PropTypes.func,
```
Comment (benbcai) [inline packages/terra-date-picker/src/DatePicker.jsx:97]: Do we still want to name this `onDismiss` or name is `onRequestClose`, similar to terra-popup and other places?

File: packages/terra-date-picker/src/DatePicker.jsx (hunk 4 above)
Comment (pranav300) [reply packages/terra-date-picker/src/DatePicker.jsx:463]: I think to keep it as a passive change we must allow both of them to be passed simultaneously. As if we give precedence to onDismiss, it is breaking the mobile view as that being a wrapped calendar requires `onClickOutside` event handler.

File: packages/terra-date-picker/src/DatePicker.jsx (hunk 1 above)
Comment (pranav300) [reply packages/terra-date-picker/src/DatePicker.jsx]: Removed it here https://github.com/cerner/terra-framework/pull/1224/commits/22d489afc2983bcb40c258881a6ed2beab768874

File: packages/terra-date-picker/src/react-datepicker/index.jsx (hunk 2 above)
Comment (pranav300) [reply packages/terra-date-picker/src/react-datepicker/index.jsx]: Added here https://github.com/cerner/terra-framework/pull/1224/commits/22d489afc2983bcb40c258881a6ed2beab768874

File: packages/terra-date-time-picker/src/DateTimePicker.jsx (hunk 3 above)
Comment (pranav300) [reply packages/terra-date-time-picker/src/DateTimePicker.jsx]: Removed it here https://github.com/cerner/terra-framework/pull/1224/commits/22d489afc2983bcb40c258881a6ed2beab768874

File: packages/terra-date-picker/src/DatePicker.jsx (hunk 4 above)
Comment (emilyrohrbough) [reply packages/terra-date-picker/src/DatePicker.jsx:462]: @pranav300 Wouldn't you pass onDismiss to the onClickOutside for now to remain passive?

Comment (pranav300) [reply packages/terra-date-picker/src/DatePicker.jsx]: `onDismiss` is being used in [setOpen](https://github.com/cerner/terra-framework/pull/1224/files#diff-0eaf044a5babfc8ff56c4b57c5220edbR471).

But yeah removing [this](https://github.com/cerner/terra-framework/pull/1224/files#diff-0eaf044a5babfc8ff56c4b57c5220edbL504), allows us to have that precedence.

File: packages/terra-date-picker/src/react-datepicker/index.jsx (hunk 5 above)
Comment (pranav300) [reply packages/terra-date-picker/src/react-datepicker/index.jsx:198]: Updated here https://github.com/cerner/terra-framework/pull/1224/commits/3ccf27db5236ebc98c306d903e3ee9329eb169df.

File: packages/terra-date-picker/src/DatePicker.jsx (hunk 4 above)
Comment (benbcai) [reply packages/terra-date-picker/src/DatePicker.jsx]: I thought was we will leave `onClickOutside` the way it is today where it is called only when clicking outside the picker to close it. We are adding `onDismiss`, which will get called whenever the picker closed (whether it be clicking outside or selecting a day). I was thinking to separate `onDismiss` with `onClickOutside` and not have them interfere with one another. Thoughts?

File: packages/terra-date-picker/src/DatePicker.jsx [hunk 7]
```diff
@@ -453,7 +459,7 @@ class DatePicker extends React.Component {
             onBlur={this.handleBlur}
             onChange={this.handleChange}
             onChangeRaw={this.handleChangeRaw}
-            onClickOutside={this.handleOnClickOutside}
+            onDismiss={onDismiss || this.handleOnClickOutside}
```
Comment (benbcai) [inline packages/terra-date-picker/src/DatePicker.jsx:462]: Should we keep `onClickOutside={this.handleOnClickOutside}` and only do `onDismiss={onDismiss}` for this [reason](https://github.com/cerner/terra-framework/pull/1224#discussion_r476666155)?

File: packages/terra-date-picker/src/react-datepicker/index.jsx [hunk 8]
```diff
@@ -499,10 +506,8 @@ class DatePicker extends React.Component {
 
   handleCalendarClickOutside = (event) => {
     if (!this.props.inline) {
-      this.setOpen(false)
+      this.setOpen(false, event)
     }
-    this.props.onClickOutside(event)
-    if (this.props.withPortal) { event.preventDefault() }
```
Comment (benbcai) [inline packages/terra-date-picker/src/react-datepicker/index.jsx:505]: We may need to keep this depending on this [decision](https://github.com/cerner/terra-framework/pull/1224/files#r476671982).

File: packages/terra-date-time-picker/src/terra-dev-site/doc/date-time-picker/Events.2.doc.mdx [hunk 9]
```diff
@@ -46,8 +46,8 @@ terra-date-time-picker has several callback events that are slightly different i
   * `isCompleteValue` - A boolean to indicate whether or not both the date and time values are filled out and conforms to the date/time format. If this boolean is false, the iSO attribute would be empty.
   * `isValidValue` - A boolean to indicate whether or not the complete date/time value is within the range of the minDate and maxDate props and is not an excluded date.
 
-### onClickOutside
-* The `onClickOutside` callback prop is triggered when clicking anywhere outside of the date picker to dismiss it.
+### onDismiss
+* The `onDismiss` callback prop is triggered when clicking anywhere outside of the date picker to dismiss it.
```
Comment (benbcai) [inline packages/terra-date-time-picker/src/terra-dev-site/doc/date-time-picker/Events.2.doc.mdx:50]: `onDismiss` would get called whenever the picker closes. Even when selecting a date so it is not limited to clicking outside.

File: packages/terra-date-picker/src/DatePicker.jsx (hunk 4 above)
Comment (pranav300) [reply packages/terra-date-picker/src/DatePicker.jsx:462]: @benbcai I do agree that providing precedence to `onDismiss` will make it a non-passive change. Therefore, I have reverted that commit here https://github.com/cerner/terra-framework/pull/1224/commits/9d8be2a715656afc67046abb501756e8ef610399. 

I think we will just have to wait to handle this in #1222.

File: packages/terra-date-picker/src/DatePicker.jsx (hunk 7 above)
Comment (pranav300) [reply packages/terra-date-picker/src/DatePicker.jsx]: Reverted here https://github.com/cerner/terra-framework/pull/1224/commits/9d8be2a715656afc67046abb501756e8ef610399

File: packages/terra-date-picker/src/react-datepicker/index.jsx (hunk 8 above)
Comment (pranav300) [reply packages/terra-date-picker/src/react-datepicker/index.jsx:505]: Updated here https://github.com/cerner/terra-framework/pull/1224/commits/9d8be2a715656afc67046abb501756e8ef610399

File: packages/terra-date-time-picker/src/terra-dev-site/doc/date-time-picker/Events.2.doc.mdx (hunk 9 above)
Comment (pranav300) [reply packages/terra-date-time-picker/src/terra-dev-site/doc/date-time-picker/Events.2.doc.mdx:50]: Updated here https://github.com/cerner/terra-framework/pull/1224/commits/e5b41a65262bc94c8d9462989d7edc89c507ff74

File: packages/terra-date-picker/src/DatePicker.jsx (hunk 6 above)
Comment (pranav300) [reply packages/terra-date-picker/src/DatePicker.jsx:97]: I think we can name it `onRequestClose`. And handle the prop [over here](https://github.com/cerner/terra-framework/blob/main/packages/terra-date-picker/src/react-datepicker/index.jsx#L425), rather than handling it in setOpen.

Comment (benbcai) [reply packages/terra-date-picker/src/DatePicker.jsx:97]: [onRequestClose](https://github.com/cerner/terra-framework/blob/main/packages/terra-date-picker/src/react-datepicker/index.jsx#L425) is only called for the popup picker in larger breakpoints. It doesn't get called for the portal picker in smaller breakpoints os setOpen would handle both workflows. Perhaps should we renamed `onDismiss` to `onRequestClose` to be more consistent with terra-popup and other places.

File: packages/terra-date-time-picker/src/terra-dev-site/doc/guides/DateTimePickerEvents.jsx [hunk 10]
```diff
@@ -65,7 +65,7 @@ class DateTimePickerEvents extends React.Component {
           <span id="onBlur-count">{this.state.blurTriggerCount}</span>
           <br />
           <br />
-          onClickOutside Trigger Count:
+          onDismiss Trigger Count:
           {' '}
           <span id="onClickOutside-count">{this.state.clickOutsideTriggerCount}</span>
```
Comment (benbcai) [inline packages/terra-date-time-picker/src/terra-dev-site/doc/guides/DateTimePickerEvents.jsx:70]: Rename `clickOutsideTriggerCount`, `clickOutsideCount`, `onClickOutside-count`, etc. This file can be cleaned up a bit by using the `useState` hook.

Comment (pranav300) [reply packages/terra-date-time-picker/src/terra-dev-site/doc/guides/DateTimePickerEvents.jsx]: Updated here https://github.com/cerner/terra-framework/pull/1224/commits/0d52d24371525054cdc6c2c7a5749c68b4b43901

File: packages/terra-date-picker/src/DatePicker.jsx (hunk 6 above)
Comment (pranav300) [reply packages/terra-date-picker/src/DatePicker.jsx]: Updated here https://github.com/cerner/terra-framework/pull/1224/commits/2f250c5b8b3b3f266e82368a847a018d45853c41

**Comment by benbcai** [comment]
Can we add a wdio or at least a jest test to cover `onRequestClose`?

**Comment by pranav300** [comment]
> Can we add a wdio or at least a jest test to cover `onRequestClose`?

Added here https://github.com/cerner/terra-framework/pull/1224/commits/1fe6ef47b3b6cbb63bcd947c5226a29e0011e3db

**Review by benbcai — APPROVED** [review]

**Review by lokesh-0813 — APPROVED** [review]

**Review by ShettyAkarsh — APPROVED** [review]

**Comment by benbcai** [comment]
@PaulSolDev This is ready for functional review. The easiest way to review this is to use this [example](https://terra-framew-deprecate--4rpntg.herokuapp.com/components/terra-date-time-picker/date-time-picker/events) and verify that the "onRequestClose Trigger Count" increments by 1 every time the picker closes, regardless of clicking outside the picker or selecting a date.

**Comment by PaulSolDev** [comment]
Functional review complete. No issues identified.
