### PR TITLE
[terra-application-navigation] Apply theme context to popupmenu and drawermenu

### LINKED ISSUE #1394: terra-application-navigation not themed for clinical-lowlight-theme
# Bug Report

## Description

When trying to view terra-application-navigation in clinical-lowlight-theme the theme variables are not being correctly applied.
https://pages.github.cerner.com/orion/orion-application/components/orion-application/demo
Screen Shot 2021-02-11 at 1 13 59 PM

## Steps to Reproduce

1. Navigate to https://pages.github.cerner.com/orion/orion-application/components/orion-application/demo
2. Switch to clinical-lowlight-theme
3. Nav Bar and portions of the Utility Menu are not themed correctly

## Additional Context / Screenshots

Screen Shot 2021-02-11 at 1 13 59 PM

## Expected Behavior

All components should be correctly themed when using a theme.

## @ Mentions

@StephenEsser @mjhenkes

### PR DESCRIPTION
**Pull request by neilpfeiffer**
### Summary

Theme context was missing for the `_DrawerMenu` and the `_PopupMenu`, therefore making the application navigation popup menu and drawer menu appear to not be themed when dynamically switching themes with devsite. 

Closes #1394   _(originally [Terra-Application#133](https://github.com/cerner/terra-application/issues/133) )_

### Deployment Link

https://terra-framew-applicatio-68zdqb.herokuapp.com/components/terra-application-navigation/application-navigation/example

### Testing

1. Go to deployment link
2. Change to lowlight-theme
3. Open User/Utilities Popup menu at large screen size
3. Open Navigation drawer at small screen size

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Review by ShettyAkarsh — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]

File: packages/terra-application-navigation/src/common/_PopupMenu.jsx [hunk 1]
```diff
@@ -2,7 +2,8 @@ import React, {
   useRef,
```
Comment (yuderekyu) [inline packages/terra-application-navigation/src/common/_PopupMenu.jsx:2]: nitpick - let's import useContext
```suggestion
  useRef,
  useContext,
```

File: packages/terra-application-navigation/src/common/_PopupMenu.jsx [hunk 2]
```diff
@@ -184,14 +185,15 @@ const PopupMenu = ({
     );
   }
 
+  const theme = React.useContext(ThemeContext);
```
Comment (yuderekyu) [inline packages/terra-application-navigation/src/common/_PopupMenu.jsx:188]: nitpick
```suggestion
  const theme = useContext(ThemeContext);
```

File: packages/terra-application-navigation/src/drawer-menu/_DrawerMenu.jsx [hunk 3]
```diff
@@ -1,6 +1,7 @@
 import React from 'react';
```
Comment (yuderekyu) [inline packages/terra-application-navigation/src/drawer-menu/_DrawerMenu.jsx:1]:
```suggestion
import React, { useContext } from 'react';
```

File: packages/terra-application-navigation/src/drawer-menu/_DrawerMenu.jsx [hunk 4]
```diff
@@ -191,9 +192,10 @@ const DrawerMenu = ({
     );
   }
 
+  const theme = React.useContext(ThemeContext);
```
Comment (yuderekyu) [inline packages/terra-application-navigation/src/drawer-menu/_DrawerMenu.jsx:195]:
```suggestion
  const theme = useContext(ThemeContext);
```

**Review by yuderekyu — APPROVED** [review]

File: packages/terra-application-navigation/src/common/_PopupMenu.jsx (hunk 1 above)
Comment (mjhenkes) [reply packages/terra-application-navigation/src/common/_PopupMenu.jsx:2]: I don't think it's wrong to use `React.useContext`. In this case i think either could be used but in some instances we use `React.useContext` to allow us to spy on the useContext method from the react object and mock it when we couldn't do that if we import it.

For instance: https://github.com/cerner/terra-framework/blob/main/packages/terra-application-utility/tests/jest/UtilityMenuDivider.test.jsx#L18

Comment (yuderekyu) [reply packages/terra-application-navigation/src/common/_PopupMenu.jsx:2]: arg, I keep on forgetting about the testing use cases. I think this should be seared in my brain now lol
