### PR TITLE
[terra-application-name][terra-application-utility] Update themeabe variables

### LINKED ISSUE #1171: [terra-application-name] Missing themeable variable
# Bug Report

**clinical-lowlight-them**

--terra-application-name-demo-background-color - packages/terra-application-name/lib/terra-dev-site/test/application-name/demoStyles.module.scss (line: 3, column: 4)

**orion-fusion-theme**

--terra-application-name-demo-background-color - packages/terra-application-name/lib/terra-dev-site/test/application-name/demoStyles.module.scss (line: 3, column: 4)

### LINKED ISSUE #1173: [terra-application-utility] Missing themeable variables
# Bug Report

The following variables are missing:

**clinical-lowlight-theme**

--terra-application-utility-header-type-menu-button-close-display - packages/terra-application-utility/lib/utility/_UtilityMenu.module.scss (line: 108, column: 4)
--terra-application-utility-header-type-menu-page-display - packages/terra-application-utility/lib/utility/_UtilityMenu.module.scss (line: 116, column: 4)

**orion-fusion-theme**

--terra-application-utility-header-type-menu-button-close-display - packages/terra-application-utility/lib/utility/_UtilityMenu.module.scss (line: 108, column: 4)
--terra-application-utility-header-type-menu-page-display - packages/terra-application-utility/lib/utility/_UtilityMenu.module.scss (line: 116, column: 4)

### PR DESCRIPTION
**Pull request by lokesh-0813**
### Summary

Packages updated
* terra-application-name
* terra-application-utitlity

Secondary Package affected due to changes
* terra-application-layout
  * Updated WDIO

Closes #1173
Closes #1171

### Deployment Link

https://terra-framework-deployed-pr-#.herokuapp.com/

### Testing

Updated WDIO

### Additional Details

Modified existing dev-site examples and tests of terra-application-name to go with theme switching.

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: packages/terra-application-name/src/terra-dev-site/doc/example/ApplicationHeaderNameStandard.jsx [hunk 1]
```diff
@@ -1,28 +1,37 @@
...
+const cy = classNamesBind.bind(styles);
+const ApplicationHeaderNameStandard = () => {
+  const theme = React.useContext(ThemeContext);
+  const demoClassName = classNames(cx(
+    'demo-background-color',
+    theme.className,
+  ));
+  return (
+    <ApplicationHeaderLayout
+      className={cy('demo-size')}
```
Comment (emilyrohrbough) [inline packages/terra-application-name/src/terra-dev-site/doc/example/ApplicationHeaderNameStandard.jsx:22]: Shouldn't theme.className be passed here?

Comment (lokesh-0813) [reply packages/terra-application-name/src/terra-dev-site/doc/example/ApplicationHeaderNameStandard.jsx:22]: No. They don't have any themeable values.
